# Generated by Django 4.1.3 on 2022-11-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('banda', models.CharField(max_length=100)),
                ('subgenero', models.CharField(max_length=100)),
                ('imagen', models.ImageField(null=True, upload_to='images/', verbose_name='Imagen')),
            ],
        ),
    ]
